Proposal: Support Overriding Object Serify Keys
karmaniverous/serify-deserify pull request #20
Opened 2023-06-04 12:33 UTC by adamaveray

In minified outputs with name mangling enabled this library's use of `constructor.name` can cause issues as the class names change during minification and between builds, and even without that issue it's impossible to register two classes with the same name.

This proposal allows optionally setting an explicit value for the library to use for an object's serify key instead of `constructor.name` through a new exported symbol `serifyKey`.

It can be used as follows:

```js
import { serifyKey } from '@karmaniverous/serify-deserify';

class CustomClass {
   static [serifyKey] = 'AlternateKey';
}

// ...

serify(data, {
  types: { AlternateKey: ... },
});
```

2023-06-05 02:33 UTC, karmaniverous requested changes
This is a great idea, thank you!

Only one change: currently the README is assembled from the set of source files in the `doc` directory, which includes a template that parses jsdoc in the source. So if you add appropriate jsdoc comments to your changes and then run `npm run package`, you'll see the changes in the README. If you want to make narrative changes to the README, make them in `/doc/1-main.md`.

if you don't do it that way, then your README changes will be overwritten by the next person who DOES do that.

Thanks for helping improve this tool!

2023-06-06 07:47 UTC, adamaveray commented
@karmaniverous Thanks for the explanation, I've just pushed a commit with that change. Let me know if you see any other issues that need updating!

2023-06-08 12:28 UTC, merged

2023-06-08 12:29 UTC, karmaniverous commented
This is great thanks @adamaveray!

2023-12-11 13:50 UTC, adamaveray commented
@karmaniverous Any chance of releasing a new NPM version incorporating this change?

2023-12-12 10:05 UTC, adamaveray commented
@karmaniverous Thank you! 🙌 Serify's been a lifesaver in one of my projects and I'm glad to be able to get rid of my manual patch now that this is released.

2023-12-13 07:57 UTC, karmaniverous commented
Ah great to hear it! Out of curiosity, how are you using it? Are you using the Redux middleware?

2024-01-02 20:28 UTC, adamaveray commented
@karmaniverous I'm using it in a React Native app that has had some issues with the (seemingly abandoned) redux-persist package which gave us some issues and of course only unserialises to basic objects which Serify let me avoid. I'm not using the middleware though – I'm manually calling it for each individual 'slice' of the store as well as for some other data stored separately outside the Redux store.

I'm also using it in various places where I need a basic JSON representation of a value for e.g. logging as a fallback when regular `JSON.stringify()` fails due to recursive references etc, so it gets a fair bit of use in the app and has made things a lot easier. Thanks again for the great library 🙌